### ISSUE TITLE
Bug: Embedded checkout session initiated even though "Enable Embedded Checkout" set to "No"

### ISSUE THREAD

**Issue by mysil2** [Dintero/Dintero.Checkout.Magento.V2#68]
**Steps to reproduce**
1. Set config "Enable Embedded Checkout" to "No"
2. Go to checkout

**Expected results**
No payment session should be initiated before clicking "Place Order"

**Actual result**
Payment session is initiated by setSession function: ``rest/default/V1/dintero/checkout/session-init`` returning checkout ID. However this ID and session is not used because Embedded Checkout is disabled. When clicking "Place Order" a new session is initiated redirecting to Dintero Checkout as it should.

**Comment by chaikovskyia** [comment]
Thanks for reporting the issue. We will look into it.

**Comment by chaikovskyia** [comment]
Thanks for reporting the issue. We will look into it.
